language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - setup=basic

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 5.5.9
      env: setup=lowest
    - php: hhvm
      dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then composer require illuminate/notifications; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.0' ]]; then composer require illuminate/notifications; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.1' ]]; then composer require illuminate/notifications; fi
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' ]]; then composer require illuminate/notifications; fi

script: vendor/bin/phpunit  --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
